AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Plaid integration backend for Financial Burndown Tracker

Parameters:
  PlaidClientId:
    Type: String
    Description: Plaid API client ID
    NoEcho: true
  PlaidSecret:
    Type: String
    Description: Plaid API secret key
    NoEcho: true
  PlaidEnv:
    Type: String
    Description: Plaid environment (sandbox, development, production)
    Default: sandbox
    AllowedValues:
      - sandbox
      - development
      - production
  AllowedOrigin:
    Type: String
    Description: CORS allowed origin (your Amplify domain or * for dev)
    Default: '*'
  S3Bucket:
    Type: String
    Description: S3 bucket storing data.json
    Default: rag-consulting-burndown
  S3Region:
    Type: String
    Description: S3 bucket region
    Default: us-west-1
  JwtSecret:
    Type: String
    Description: Secret key for signing JWTs
    NoEcho: true
  PlaidMonthlyBudget:
    Type: String
    Description: Max monthly Plaid spend in dollars (default $10)
    Default: '10'
  PlaidEstCostPerCall:
    Type: String
    Description: Estimated cost per Plaid API call in dollars (default $0.10)
    Default: '0.10'
  PlaidMaxSyncPages:
    Type: String
    Description: Max pagination pages per sync call (prevents runaway loops)
    Default: '10'
  PlaidSyncCooldownSeconds:
    Type: String
    Description: Minimum seconds between syncs for the same item
    Default: '300'

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64
    Environment:
      Variables:
        PLAID_CLIENT_ID: !Ref PlaidClientId
        PLAID_SECRET: !Ref PlaidSecret
        PLAID_ENV: !Ref PlaidEnv
        TOKENS_TABLE: !Ref PlaidTokensTable
        S3_BUCKET: !Ref S3Bucket
        S3_REGION: !Ref S3Region
        ALLOWED_ORIGIN: !Ref AllowedOrigin
        JWT_SECRET: !Ref JwtSecret
        USERS_TABLE: !Ref UsersTable
        ORGS_TABLE: !Ref OrganizationsTable
        ORG_MEMBERS_TABLE: !Ref OrgMembersTable
        PLAID_MONTHLY_BUDGET: !Ref PlaidMonthlyBudget
        PLAID_EST_COST_PER_CALL: !Ref PlaidEstCostPerCall
        PLAID_MAX_SYNC_PAGES: !Ref PlaidMaxSyncPages
        PLAID_SYNC_COOLDOWN_SECONDS: !Ref PlaidSyncCooldownSeconds

  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # ---------- DynamoDB ----------
  PlaidTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PlaidTokens
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: itemId
          KeyType: RANGE

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BurndownUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  OrganizationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Organizations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orgId
          AttributeType: S
        - AttributeName: joinCode
          AttributeType: S
      KeySchema:
        - AttributeName: orgId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: joinCode-index
          KeySchema:
            - AttributeName: joinCode
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  OrgMembersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrgMembers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: orgId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: orgId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # ---------- Org Lambda Functions ----------
  OrgCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/orgCreate.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrgMembersTable
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/org/create
            Method: post

  OrgJoinFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/orgJoin.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrgMembersTable
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/org/join
            Method: post

  OrgGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/orgGet.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrgMembersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/org
            Method: get

  OrgRegenerateCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/orgRegenerateCode.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrganizationsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/org/regenerate-code
            Method: post

  # ---------- Auth Lambda Functions ----------
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/register.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/register
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/login.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/login
            Method: post

  VerifyMfaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/verifyMfa.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/verify-mfa
            Method: post

  SetupMfaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/setupMfa.setupHandler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/setup-mfa
            Method: post

  EnableMfaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/setupMfa.enableHandler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/enable-mfa
            Method: post

  MeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/me.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/auth/me
            Method: get

  # ---------- Plaid Lambda Functions ----------
  PlaidLinkTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/linkToken.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/link-token
            Method: post

  PlaidExchangeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/exchange.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/exchange
            Method: post

  PlaidSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/sync.handler
      CodeUri: .
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/sync
            Method: post

  PlaidAccountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/accounts.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/accounts
            Method: get

  PlaidDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/disconnect.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/disconnect
            Method: post

  PlaidBudgetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/budget.handler
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PlaidTokensTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /plaid/budget
            Method: get

  # ---------- Data API (secured S3 proxy) ----------
  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getData.handler
      CodeUri: .
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/data
            Method: get

  PutDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/putData.handler
      CodeUri: .
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/data
            Method: put

  GetStatementsIndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getStatements.handler
      CodeUri: .
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/statements
            Method: get

  GetStatementByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/getStatements.handler
      CodeUri: .
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref S3Bucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/statements/{statementId}
            Method: get

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PlaidTokensTableName:
    Description: DynamoDB table for Plaid tokens
    Value: !Ref PlaidTokensTable
